## output directories
derivatives: derivatives
xray_from_ct: xray_from_ct
xray_from_ct_angle_perturbation: xray_from_ct_angle_perturbation
xray_from_ct_patch: xray_from_ct_patch
xray_from_mask: xray_from_mask
xray_from_ctmask: xray_rom_ctmask
seg_roi: seg_roi
seg_roi_patch: seg_roi_patch
ct_roi: ct_roi
ct_mask_roi: ct_mask_roi
centroid: centroid_roi
overlay: overlay
